title: Default Page


sections:
   content:
      type: fields
      fields:
        intro:
          label: Info
          type: text
          width: 2/3
   
   Images:
      type: files
      layout: cards
      image:
        cover: true
        ratio: 1/1
        
      

